/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jstring JNICALL Java_com_example_opencvjniapplication_NativeClass_getStringFromNative
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_example_opencvjniapplication_convertNativeGray(JNIEnv*, jobject, jlong addrRgba, jlong addrGray);

#ifdef __cplusplus
}
#endif